### PR TITLE
Added MatTransform functions; added constexpr to Object3d.hpp

### PR DESCRIPTION
**Pull request by sts1skj**
- Added functions to MatTransform: ToGLMMatrix, ApplyTransformToDiff, ApplyTransformToDir, and ApplyTransformToDist.
- Made MatTransform::ApplyTransform an inline function.
- Added some constructors for Matrix3.
- Made many of the functions in Object3d.hpp constexpr.  For some, this necessitated changes to the implementation in order to comply with the rules for constexpr functions, but in no case was functionality changed.  I was not thorough; there are lots of functions that could still be made constexpr.

### CODE REVIEW

**Comment by sts1skj** [comment]
Along the way, I noticed a number of operator overloads in Object3d.hpp that I would prefer were named functions instead of operators, because the functionality of these functions does not match standard vector math conventions:
Vector3& Vector3::operator*=(const Vector3& other)
Vector3 Vector3::operator*(const Vector3& other) const
Vector3& Vector3::operator/=(const Vector3& other)
Vector3 Vector3::operator/(const Vector3& other) const
Vector3 Matrix3::operator*(float f) const

The last is particularly problematic, as there is a standard meaning for multiplying a matrix by a scalar that gives a matrix, not a vector.

I suggest renaming these functions to:
ComponentMultiplyBy
ComponentMultiply
ComponentDivideBy
ComponentDivide
MultiplyByIdenticalComponentVector

In the last case, though, I think it would be better to get rid of the function altogether.

May I make these changes?

**Comment by sts1skj** [comment]
I dislike some of the function names in MatTransform.  I'd like to change them as follows:
ApplyTransform -> ApplyToPos
ApplyTransformToDiff -> ApplyToDiff
ApplyTransformToDir -> ApplyToDir
ApplyTransformToDist -> ApplyToDist
InverseTransform -> Inverse
ComposeTransforms -> Compose

Three of these functions are new to this PR; the rest are old.  May I change these function names?

**Comment by ousnius** [comment]
@sts1skj Now that nifly is a library that's already being used by multiple other active projects, we cannot really rename (often used) classes or functions just like that. At the very least, it would require marking it as a new release in some form and letting people know of the "API" change.

The changes currently made by the PR should be fine.

Instead of removing/renaming, you could add the following functions in addition to the current operators:
ComponentMultiplyBy
ComponentMultiply
ComponentDivideBy
ComponentDivide

Is ``Vector3 Matrix3::operator*(float f) const`` currently being used by nifly or Outfit Studio?

**Comment by sts1skj** [comment]
`Vector3 Matrix3::operator*(float f) const` is only used in the function MatTransform::GetVector, which is not used anywhere in nifly or Outfit Studio.  GetVector does something that seems nonsensical to me.

**Comment by sts1skj** [comment]
May I apply the C++-2014 "deprecated" attribute to the five operators and to GetVector?

**Comment by ousnius** [comment]
> May I apply the C++-2014 "deprecated" attribute to the five operators and to GetVector?
Yes.

**Pull request merged**
